- hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
     - ansible-local-setup 

- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  roles:
     - petclinic  
